---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: source-lister
spec:
  params:
    - name: contextDir
      description: "The context directory within the repository for sources"
      default: ""
    - name: lsArgs
      description: "Arguments to pass to ls"
      default: "-ltr"
  workspaces:
    - name: source
      description: Workspace to list
  steps:
    - name: ls-build-sources
      image: registry.redhat.io/rhel8/python-38
      # command: ["ls", "$(inputs.params.lsArgs)", "$(workspaces.source.path)/$(inputs.params.contextDir)"]
      script: |
        echo "Running ls on '$(workspaces.source.path)' with contextDir '$(inputs.params.contextDir)'"
        ls $(inputs.params.lsArgs) $(workspaces.source.path)/$(inputs.params.contextDir)
        ls -alh /workspace

